name: Smoke test

on:
  schedule:
    - cron: '0 0 * * THU'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.11
    - run: yarn install
    - run: yarn build
    - run: yarn install
      working-directory: ./smoke-test
    - run: yarn test
      working-directory: ./smoke-test
      env:
        CI: true